version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: viewz_db
    environment:
      POSTGRES_USER: viewz
      POSTGRES_PASSWORD: viewzpass
      POSTGRES_DB: viewz
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U viewz -d viewz"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

